package com.example.productandpayment.service;

import com.example.productandpayment.paymentGateways.PaymentGateway;
import com.razorpay.RazorpayException;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

@Service
public class PaymentService {
    private PaymentGateway paymentGateway;

    public PaymentService(@Qualifier("razorpayPaymentGateway") PaymentGateway paymentGateway) {
        this.paymentGateway = paymentGateway;
    }

    public String initiatePayment(Long orderid, Long amount, String phoneNumber) throws RazorpayException {
        // We need to make a call to the PG and return the
        // payment link generated by the PG

        return paymentGateway.generatePaymentLink(orderid, amount, phoneNumber);
    }
}
